version: 2.1

jobs:
  Build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: npm install --save

  Build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: build docker image
          command: |
            docker build -t nodejswebapp -t adijaiswal/nodejswebapp:latest .
            echo $DOCKER_PASSWORD | docker login -u adijaiswal --password-stdin
            docker push adijaiswal/nodejswebapp:latest

workflows:
  version: 2
  Build_test:
    jobs:
      - Build_test
      - Build_docker_image
